"""Add invoice_sequences

Revision ID: 79a4588b01bd
Revises: a1b2c3d4e5f6
Create Date: 2026-08-22 13:56:20.658126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79a4588b01bd'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_sequences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('invoice_date', sa.String(length=10), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'invoice_date', name='uix_invoice_sequence_user_date')
    )
    op.execute("ALTER TABLE invoice_sequences ENABLE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY \"Users can manage their own invoice sequences\" "
        "ON invoice_sequences "
        "FOR ALL "
        "USING (user_id = auth.uid()) "
        "WITH CHECK (user_id = auth.uid());"
    )
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_unique_constraint('uix_invoice_user_number', 'invoices', ['created_by', 'invoice_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_invoice_user_number', 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=True)
    
    op.execute("DROP POLICY IF EXISTS \"Users can manage their own invoice sequences\" ON invoice_sequences;")
    op.drop_table('invoice_sequences')
    # ### end Alembic commands ###
