"""Add business profile fields

Revision ID: f5ad76b109d9
Revises: a646af8b4d40
Create Date: 2026-08-22 22:22:50.049476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5ad76b109d9'
down_revision: Union[str, None] = 'a646af8b4d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_owner_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'profiles', ['owner_id'], ['id'])
    op.alter_column('google_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('google_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('invoices_created_by_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'profiles', ['created_by'], ['id'])
    op.drop_index('ix_mobile_verifications_mobile_number', table_name='mobile_verifications')
    op.create_index(op.f('ix_mobile_verifications_mobile_number'), 'mobile_verifications', ['mobile_number'], unique=True)
    op.drop_constraint('products_owner_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'profiles', ['owner_id'], ['id'])
    op.add_column('profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('profiles', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('gst_number', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('business_address', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('company_logo_url', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('profile_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('profiles', sa.Column('invoice_prefix', sa.String(length=20), server_default='INV', nullable=False))
    op.add_column('profiles', sa.Column('invoice_numbering_preference', sa.String(length=20), server_default='sequential', nullable=False))
    op.add_column('profiles', sa.Column('payment_terms', sa.String(length=200), nullable=True))
    op.add_column('profiles', sa.Column('tax_settings', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('upi_id', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('bank_details', sa.Text(), nullable=True))
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('profiles', 'mobile_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('profiles', 'shop_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('profiles', 'role',
               existing_type=postgresql.ENUM('owner', 'staff', name='user_role'),
               nullable=False,
               existing_server_default=sa.text("'owner'::user_role"))
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_index(op.f('ix_profiles_mobile_number'), 'profiles', ['mobile_number'], unique=True)
    op.drop_constraint('profiles_id_fkey', 'profiles', type_='foreignkey')
    op.drop_constraint('stock_transactions_created_by_fkey', 'stock_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'stock_transactions', 'profiles', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.create_foreign_key('stock_transactions_created_by_fkey', 'stock_transactions', 'profiles', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('profiles_id_fkey', 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_index(op.f('ix_profiles_mobile_number'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'role',
               existing_type=postgresql.ENUM('owner', 'staff', name='user_role'),
               nullable=True,
               existing_server_default=sa.text("'owner'::user_role"))
    op.alter_column('profiles', 'shop_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('profiles', 'mobile_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('profiles', 'bank_details')
    op.drop_column('profiles', 'upi_id')
    op.drop_column('profiles', 'website')
    op.drop_column('profiles', 'tax_settings')
    op.drop_column('profiles', 'payment_terms')
    op.drop_column('profiles', 'invoice_numbering_preference')
    op.drop_column('profiles', 'invoice_prefix')
    op.drop_column('profiles', 'profile_completed')
    op.drop_column('profiles', 'company_logo_url')
    op.drop_column('profiles', 'business_address')
    op.drop_column('profiles', 'gst_number')
    op.drop_column('profiles', 'phone')
    op.drop_column('profiles', 'company_name')
    op.drop_column('profiles', 'email')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_owner_id_fkey', 'products', 'profiles', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_mobile_verifications_mobile_number'), table_name='mobile_verifications')
    op.create_index('ix_mobile_verifications_mobile_number', 'mobile_verifications', ['mobile_number'], unique=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_created_by_fkey', 'invoices', 'profiles', ['created_by'], ['id'], ondelete='CASCADE')
    op.alter_column('google_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('google_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_owner_id_fkey', 'categories', 'profiles', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
